name = "MolSimToolkit"
uuid = "054db54f-6694-444d-9bbb-e9ecdbfe77be"
authors = ["Leandro Martinez <lmartine@unicamp.br> and contributors"]
version = "1.0.1-DEV"

[deps]
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
CellListMap = "69e1c6dd-3888-40e6-b3c8-31ac5f578864"
Chemfiles = "46823bd8-5fb3-5f92-9aa0-96921f3dd015"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
EasyFit = "fde71243-0cda-4261-b7c7-4845bd106b21"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PDBTools = "e29189f1-7114-4dbd-93d0-c5673a921a58"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
BlockAveragesPlotting = "Plots"

[compat]
Aqua = "0.7"
AtomsBase = "0.3.4"
BenchmarkTools = "1.3"
CellListMap = "0.8"
Chemfiles = "0.10.31"
DocStringExtensions = "0.8, 0.9"
EasyFit = "0.6"
LaTeXStrings = "1.3"
LinearAlgebra = "1.9"
PDBTools = "0.14.2, 0.15"
Printf = "1.9"
Plots = "1.39"
Reexport = "1.2.2"
StaticArrays = "1.6"
Statistics = "1"
StatsBase = "0.34"
TestItemRunner = "0.2.1"
TestItems = "0.1.1"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Aqua", "Test", "TestItemRunner", "BenchmarkTools"]
