name = "MolSimToolkit"
uuid = "054db54f-6694-444d-9bbb-e9ecdbfe77be"
authors = ["Leandro Martinez <lmartine@unicamp.br> and contributors"]
version = "1.22.2-DEV"

[deps]
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
CellListMap = "69e1c6dd-3888-40e6-b3c8-31ac5f578864"
Chemfiles = "46823bd8-5fb3-5f92-9aa0-96921f3dd015"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
EasyFit = "fde71243-0cda-4261-b7c7-4845bd106b21"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
PDBTools = "e29189f1-7114-4dbd-93d0-c5673a921a58"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
ProteinSecondaryStructures = "c298f58b-271f-48cb-96ac-5442ca7c67d9"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
Plotting = "Plots"

[compat]
Aqua = "0.8"
AtomsBase = "0.3.4, 0.4, 0.5"
BenchmarkTools = "1.3"
CellListMap = "0.9.6"
Chemfiles = "0.10.31"
Dates = "1.9"
DelimitedFiles = "1.9"
DocStringExtensions = "0.9"
Documenter = "1.3"
EasyFit = "0.6.8"
LaTeXStrings = "1.3"
LinearAlgebra = "1.9"
OffsetArrays = "1.13"
PDBTools = "1.8.1, 2"
Plots = "1.39"
ProgressMeter = "1.10"
ProteinSecondaryStructures = "2"
Reexport = "1.2.2"
Rotations = "1.7"
StaticArrays = "1.6"
Statistics = "1.9"
StatsBase = "0.34"
Test = "1.9"
TestItemRunner = "1"
TestItems = "1"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Aqua", "Test", "TestItemRunner", "BenchmarkTools", "DelimitedFiles", "Rotations", "Documenter", "Plots"]
