[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
MolSimToolkit = "054db54f-6694-444d-9bbb-e9ecdbfe77be"
PDBTools = "e29189f1-7114-4dbd-93d0-c5673a921a58"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
